// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1oEkUxC2j44Mz2Kz9UuHDy7Uy5XksXZQ',
    appId: '1:175501487996:web:3c6f9d2458931593ae3ef9',
    messagingSenderId: '175501487996',
    projectId: 'powershare-b6d6d',
    authDomain: 'powershare-b6d6d.firebaseapp.com',
    storageBucket: 'powershare-b6d6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4K2I0zQb5jMnN8GoE4WtPFQw4fgV40eA',
    appId: '1:175501487996:android:af1bbf3ce85f28c3ae3ef9',
    messagingSenderId: '175501487996',
    projectId: 'powershare-b6d6d',
    storageBucket: 'powershare-b6d6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBISbfzUL4eds5IjbuielLYZEgsL3duwYI',
    appId: '1:175501487996:ios:ce79c5af864b647dae3ef9',
    messagingSenderId: '175501487996',
    projectId: 'powershare-b6d6d',
    storageBucket: 'powershare-b6d6d.appspot.com',
    iosBundleId: 'com.example.powershare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBISbfzUL4eds5IjbuielLYZEgsL3duwYI',
    appId: '1:175501487996:ios:05bdcb5dcbfcb7b4ae3ef9',
    messagingSenderId: '175501487996',
    projectId: 'powershare-b6d6d',
    storageBucket: 'powershare-b6d6d.appspot.com',
    iosBundleId: 'com.example.powershare.RunnerTests',
  );
}
